version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER : "postgres"
      POSTGRES_PASSWORD: "post"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - "postgres"
volumes:
  pgdata:
  pgconf:
  pglog:
  pgadmindata:
networks:
  default:
    external: true
    name: home-network